### ISSUE TITLE
Save and Exit

### ISSUE THREAD

**Issue by AlejandroLoutphi** [AlejandroLoutphi/MetroMendeleyLoutphiRuizZaherAlDeen#9]
I'm not quite sure what the teacher wants here yet
Right now, just update the file where all the abstracts are with the current list I guess

**Comment by AlejandroLoutphi** [comment]
Note: @ayahza369 had a better idea involving saving all uploaded files as a String and appending it to the end of the current Investigations.txt file

**Comment by ayahza369** [comment]
COMPLETED. IMPLEMENTATION LEFT ONCE MAINFRAME IS COMPLETE
